import { createClient } from "next-sanity";
// import { apiVersion, dataset, projectId, useCdn } from '../env'

// using enviornment variables
const projectID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET;
const token = process.env.NEXT_PUBLIC_SANITY_TOKEN;

// setting the client
export const client = createClient({
  apiVersion: "2023-06-05",
  projectId: projectID, // automatically generated by sanity
  dataset: dataset, // automatically generated by sanity
  token: token, // create a token at sanity website ap section
  useCdn: true,
});
