import "./globals.css";
// Internal Imports
// import Navbar from "@/components/Navbar";
// import MobileMenu from "@/components/MobileMenu";
import Info from "@/components/Info";
import Footer from "@/components/Footer";
import Wrapper from "@/components/Wrapper";
import NavWrapper from "@/components/NavWrapper";
export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

// Provider
import Providers from "@/components/Provider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Wrapper>
            <nav>
              {/* <Navbar />
            <MobileMenu /> */}
              <NavWrapper />
            </nav>
            {children}
            <footer>
              <Info />
              <Footer />
            </footer>
          </Wrapper>
        </Providers>
      </body>
    </html>
  );
}
